version: '3.7'
services:
  spring-boot-live-reload:
    image: adoptopenjdk/openjdk11:slim
    volumes:
      - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    ports:
      - 8080:8080
